sudo: required
services:
- docker
language: go
go:
- 1.8
env:
  global:
  - PATH=/home/travis/gopath/bin:$PATH DEBIAN_FRONTEND=noninteractive
  - secure: "bE6r2vPDjGyRvkCLlaeZtpSBIheNwq565DsO/DZpYkmjCcPcJSFH2Xvox92uYMkh8T5DHLZ6FxP+TVJSLsZrO75mhy8X3T/cz6CjoEiQLrsFu2eH3N1cLsEBpS99NVS8sZfnyMuplsPpC/mMjdQ43mGQbIpUukSme/PClsQy2wg="
addons:
  apt:
    packages:
      - devscripts
      - debhelper
      - dh-systemd
install:
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make lint
- make cover
- test `gofmt -l . | wc -l` = 0
- make crossbuild
after_script:
- goveralls -coverprofile=.profile.cov
before_deploy:
- docker pull astj/mackerel-rpm-builder:c5
- docker pull astj/mackerel-rpm-builder:c7
- make rpm deb rpm-kcps deb-kcps rpm-stage deb-stage tgz
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=1000
- git fetch --tags --depth=1000 || true
deploy:
- provider: script
  script: _tools/releng --task=upload-to-github-release && _tools/releng --task=upload-master-to-github-release
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: _tools/releng --task=create-pullrequest --current-branch=$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
notifications:
  slack:
    secure: n9Hs5rIlb6MuFVsRp46ykd+CptnE3boI7Q9mNLuHwz77IQ/2mpUmOyBRDeW3BA2EXa4WEYAXu8q7/b7zVV+c+RcPdz8/h9N9EBrHUVeIkCP/Nyp+aUA8GvLNjGuxYC7nov3L+9GHBFXKX8FaV2lZ1/Eeb1Ovbtv6Oi39xNkHqTQ=
